### ISSUE TITLE
What do you use it for?

### ISSUE THREAD

**Issue by jzabroski** [aaasoft/Quick.Protocol#1]
Hi,

Came searching for a nicer Wrapping of SerialPort API and general Socket connections API.

**Comment by aaasoft** [comment]
I use it for our company products.Client program communicate to Server program with private protocol.Client can send command to server and server can send data to client.

**Comment by jzabroski** [comment]
Hi @aaasoft 

Sorry if this is bothering you.  Just wanted to discuss best practices, and you seem like a bright and excellent engineer worth discussing things with.

I noticed in your tests, they're not automated.  Have you thought about using [MbDotNet](https://www.nuget.org/packages/MbDotNet) to mock the client and the server separately, and exercise your tests through Fixie or xUnit?

**Comment by aaasoft** [comment]
@jzabroski 
Test server and client is separately. when you want to run the test,start Test Server first and then start Test Client.

Test Server:
https://github.com/aaasoft/Quick.Protocol/tree/master/Test/Tcp/TcpServer

Test Client:
https://github.com/aaasoft/Quick.Protocol/tree/master/Test/Tcp/TcpClient

**Comment by jzabroski** [comment]
That's precisely my point.  You've tightly coupled the two and cant mock them.
